# common configuration for ALL branches
image: Visual Studio 2017
version: '1.6.{build}'
init:
- git config --global core.autocrlf true
build_script:
- ps: .\build.ps1 -Target Test --BuildVersion=$($env:appveyor_build_version)
test: off
artifacts:
- path: BuildArtifacts\*.nupkg
  name: NuGet package
cache:
- packages -> **\packages.config      
- tools -> build.cake
skip_commits:
  files:
  - license.txt
  - readme.md
  - how-to-build.md

# here we are going to override common configuration
for:

# master branch
-
  branches:
    only:
      - master  
  build_script:
  - ps: .\build.ps1 -Target Publish --BuildVersion=$($env:appveyor_build_version) 
  deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: c+mL8DX3ln4s/VMJ8jYBuaV/HAwexKKQZLKVBF9w7q+iONNow5WH4gn1AglAS/wX